name: caphe_quanly
description: "Coffee Shop Manager - Ung dung quan ly quan ca phe"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  go_router: ^14.8.1
  shared_preferences: ^2.3.4
  fl_chart: ^0.70.2
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  pdf: ^3.11.2
  printing: ^5.13.5
  json_annotation: ^4.9.0
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
